name: S3 Upload Test

on:
  push:
    branches:
      - master

jobs:
  test-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      # 1. 빌드 과정 대신 테스트용 임시 폴더와 파일을 만듭니다.
      - name: Create Test File
        run: |
          mkdir test-build
          echo "<h1>Hello S3! S3 Upload is Working!</h1>" > test-build/index.html

      # 2. 방금 만든 임시 폴더(test-build)를 S3에 업로드합니다.
      - name: Sync to S3 Bucket
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_EC2_METADATA_DISABLED: true
        run: |
          aws s3 sync \
            --region eu-north-1 \
            test-build s3://github-action-s3-cd \
            --delete
